CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    uuid VARCHAR(255) UNIQUE,
    gender VARCHAR(10),
    title VARCHAR(10),
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    email VARCHAR(255),
    phone VARCHAR(50),
    cell VARCHAR(50),
    date_of_birth DATE,
    age INTEGER,
    nationality VARCHAR(10),
    street_number INTEGER,
    street_name VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(100),
    country VARCHAR(100),
    postcode VARCHAR(20),
    latitude DECIMAL(10, 8),
    longitude DECIMAL(11, 8),
    timezone_offset VARCHAR(10),
    timezone_description VARCHAR(255),
    username VARCHAR(100),
    password VARCHAR(255),
    salt VARCHAR(255),
    md5 VARCHAR(255),
    sha1 VARCHAR(255),
    sha256 VARCHAR(255),
    picture_large VARCHAR(500),
    picture_medium VARCHAR(500),
    picture_thumbnail VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);